version: 2

jobs:
  deploy:
    working_directory: ~/batata
    docker:
      - image: circleci/node:12.4.0
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
    steps:
      - checkout
      - attach_workspace:
          at: ~/batata
      - run:
          name: Install packages
          command: npm ci

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
