name: deployment

on:
  push:
    branches:
      - master

env:
  CI: true
  NG_CLI_ANALYTICS: false
  NODE_VERSION: 12.x

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore Dependencies
        id: node-modules-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}

  release:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Repository
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        if: github.ref == 'refs/heads/master'
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore Dependencies
        if: github.ref == 'refs/heads/master'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Generate Release
        if: github.ref == 'refs/heads/master'
        env:
          RELEASE_DOCS_PROJECT_ID: semantic-test
          RELEASE_DOCS_AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_DOCS_AWS_ACCESS_KEY_ID }}
          RELEASE_DOCS_AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.RELEASE_DOCS_AWS_SECRET_ACCESS_KEY_ID }}
          RELEASE_DOCS_AWS_BUCKET: ${{ secrets.RELEASE_DOCS_AWS_BUCKET }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          CHANGELOG_TITLE: "https://changelog.wellabe.fit"
        run: npm run semantic-release

  skip-ci:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Skip CI
        run: echo "Deploy triggered by semantic release. Skipping all jobs."
